name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEPLOYMENT_HOST }}
          username: ${{ secrets.DEPLOYMENT_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            DEPLOY_USER="${{ secrets.DEPLOYMENT_USER }}"
            cd /home/${DEPLOY_USER}/ratwork_mechanism_bot
            OLD_REVISION=$(git rev-parse HEAD)
            git pull --rebase origin main
            NEW_REVISION=$(git rev-parse HEAD)
            if [ "$OLD_REVISION" != "$NEW_REVISION" ]; then
              if git diff --name-only "$OLD_REVISION" "$NEW_REVISION" | grep -q "^requirements.txt$"; then
                echo "requirements.txt changed, reinstalling dependencies"
                /home/${DEPLOY_USER}/ratwork_mechanism_bot/venv/bin/pip install -r requirements.txt
              fi
              sudo systemctl restart ratwork.service
            fi
